### ISSUE TITLE
Typing into a cell loses focus after every key press

### ISSUE THREAD

**Issue by m-r-hunt** [don-tnowe/godot-resources-as-sheets-plugin#22] opened 2023-04-30 00:57 UTC
This is in Godot 4.0.2. Title says it all, if I'm typing into a cell like a string or number, it loses focus after every key press. I can only type one character at a time and need to reselect the cell to continue. Makes it basically unusable.

There are some other errors appearing in the console which I can detail if it's helpful but they appear to be unrelated at a casual glance.

**Comment by don-tnowe** [comment] 2023-04-30 13:47
I'm not getting this behaviour. No errors for me too, so they seem related.

What are the errors?

**Comment by m-r-hunt** [comment] 2023-04-30 16:33
Here's the full console output after I've loaded up my project, opened a resource folder and typed one character into a string field:

```
Godot Engine v4.0.3.rc.custom_build (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  scene\resources\resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_editors/dock_texture.tscn:4 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png
  Resource file not found: res://icon.png.
  scene\resources\resource_format_text.cpp:174 - res://addons/resources_spreadsheet_view/typed_editors/dock_texture.tscn:51 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon.png
  scene\resources\resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:3 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png
  Resource file not found: res://icon.png.
  scene\resources\resource_format_text.cpp:174 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:41 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon.png
  scene\resources\resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:3 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png
  Resource file not found: res://icon.png.
  scene\resources\resource_format_text.cpp:174 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:41 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon.png
  scene\resources\resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:3 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png
  Resource file not found: res://icon.png.
  scene\resources\resource_format_text.cpp:174 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:41 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon.png
Set Cell Values
  scene\resources\resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:3 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png
  Resource file not found: res://icon.png.
  scene\resources\resource_format_text.cpp:174 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:41 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon.png
  scene\resources\resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:3 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png
  Resource file not found: res://icon.png.
  scene\resources\resource_format_text.cpp:174 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:41 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon.png
  scene\resources\resource_format_text.cpp:448 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:3 - ext_resource, invalid UID: uid://c08qavfwqr3k7 - using text path instead: res://icon.png
  Resource file not found: res://icon.png.
  scene\resources\resource_format_text.cpp:174 - res://addons/resources_spreadsheet_view/typed_cells/resource.tscn:41 - Parse Error: [ext_resource] referenced non-loaded resource at: res://icon.png
  ```
  
  The errors about `res://icon.png` will go away if I open and resave those scenes (it's worth noting that `res://icon.png` doesn't exist any more in default Godot 4 generated projects, there's a `res://icon.svg` instead).
  
  Then I get this error instead:
  
  ```
  Godot Engine v4.0.3.rc.custom_build (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
--- Debug adapter server started ---
--- GDScript language server started ---
  res://addons/resources_spreadsheet_view/main_screen/column_header_manager.gd:89 - Invalid get index 'size' (on base: 'previously freed').
Set Cell Values
```

**Comment by m-r-hunt** [comment] 2023-04-30 16:43
I tried setting up a new project and a test script to see if I could provide a minimal test project and it's not happening. Must be something specific that I've done in my project. I'll have a look and see if I can figure out what's triggering this to happen.

**Comment by m-r-hunt** [comment] 2023-04-30 16:47
I've worked out what was causing the bug. It's when I have other file types in the same folder as the resource I'm editing. I had the script the resources were using in the same folder as the resources themselves. Here's an example that does it for me:

[test_sheets.zip](https://github.com/don-tnowe/godot-resources-as-sheets-plugin/files/11361790/test_sheets.zip)

Obviously I can work around this by having the resources in their own folder with nothing else, but it would still be nice to fix this bug.

**Comment by don-tnowe** [comment] 2023-05-01 07:47
Found the cause. I'm checking, when the `filesystem_changed` signal fires, whether the list of files has actually changed. The file counts are sourced from different places, hence mismatch.

Here's another workaround: the inspector can be used, but multi-cell edit with it overwrites all text in selected cells (*can set, can't append/insert*).

Thanks for reporting!

**Comment by don-tnowe** [comment] 2023-05-01 08:21
Should be fixed.

**Comment by m-r-hunt** [comment] 2023-05-01 08:53
I've tried it out and it seems to be working fine on my examples now.

**Closed** 2023-05-01 15:03 UTC
Labels: bug, testing
